### ISSUE TITLE
Tambah Plugins

### ISSUE THREAD

**Issue by n2ng-dev** [pojokcodeid/nvim-lazy#1]
Halo bang

bagaimana menambahkan plugins flutter-tools untuk coding flutter ?
https://github.com/akinsho/flutter-tools.nvim.git

thanks bang

**Comment by pojokcodeid** [comment]
- documentasi dan tutorial nanti saya tambahkan, untuk acuan mungkin bisa di coba ini
- https://astronvim.github.io/Recipes/advanced_lsp#rust-rust-toolsnvim

**Comment by pojokcodeid** [comment]
silahkan ikuti panduan berikut 
https://github.com/pojokcodeid/nvim-lazy/wiki/6.-Configurasi#config-flutter-tool

**Comment by pojokcodeid** [comment]
done

**Comment by pojokcodeid** [comment]
done

**Comment by n2ng-dev** [comment]
terimakasih banyak bang

sukse terus
