### ISSUE TITLE
nvim-lazy gagal terinstall terus

### ISSUE THREAD

**Issue by ifqygazhar** [pojokcodeid/nvim-lazy#2]
Hallo ini kenapa ya nge clone nvim-lazy nya error terus, sudah saya coba sync dan install berulang kali tetep begini

![Screenshot_2023-07-28-08-59-36_1366x768](https://github.com/pojokcodeid/nvim-lazy/assets/82558488/f3409105-67f0-4005-a62e-1fee40b18fd0)

**Comment by pojokcodeid** [comment]
Hai

ini menggunakan config yang mana
sudah mengikuti tutorial yang di youtube?

**Comment by pojokcodeid** [comment]
kami test tidak ada kenala, silahkan di coba kembali
![image](https://github.com/pojokcodeid/nvim-lazy/assets/68836805/c9d35d79-fbcb-49ba-81a7-8f9261255294)

**Comment by pojokcodeid** [comment]
tidak terjadi msalah
