### ISSUE TITLE
jdtls not worlking 

### ISSUE THREAD

**Issue by hkhrithik007** [pojokcodeid/nvim-lazy#4]
jdtls is nor working anyway

**Comment by pojokcodeid** [comment]
Follow :
https://youtu.be/CEJZjz_lAKM
Or
https://youtu.be/kPr-X4l94BA

**Comment by pojokcodeid** [comment]
already OK test windows and linux
test use JDK 17 and gradle 7.6
https://www.openlogic.com/openjdk-downloads
https://services.gradle.org/distributions/
