### ISSUE TITLE
Flutter-tool not working

### ISSUE THREAD

**Issue by akhsanuwNadia** [pojokcodeid/nvim-lazy#6]
saya sudah mengikuti tutorial yg dari yt,
dan flutter-tool sudah ter-loaded di lazy.
tapi ketika membuka project flutter saya - ls inactive - flutter-tool [dartls, dart_format] tidak berjalan ketika membuka file dart

**Comment by pojokcodeid** [comment]
apakah dart lsp sudah diinstall?
apakah dart projek di create menggunakan commond dart ?
saya coba berjalan LSP nya

**Comment by akhsanuwNadia** [comment]
solved.
untuk error ternyata bukan di dart lsp, tapi di file "ftplugin/dart.lua" - module dap belum terinstall.
setelah menginstall "mfussenegger/nvim-dap" flutter-tool [lsp, formating] berjalan dengan baik.

dan terimakasih sudah membuat tutorial neovim config 
karena IDE (android studio) sebelumnya sudah sangat berat untuk device saya (T_T)
