### ISSUE TITLE
Error executing lua [string ":lua"]:1: attempt to call field 'bufremove' (a nil value)

### ISSUE THREAD

**Issue by rezafikkri** [pojokcodeid/nvim-lazy#7]
Jadi saya baru install confignya, sesuai dokumentasi, tanpa ada custom config apapun, dan berhasil. 

- versi neovim: 0.10.0
- os: linux debian 12
- terminal: kitty versi 0.34.1

Error ini terjadi ketika saya menekan <leader>bc untuk close current buffer.

Terima kasih. Btw saya suka nih confignya, sebelumnya saya pakai lunarvim, tapi config yang ini lebih cocok.

**Comment by pojokcodeid** [comment]
sudah dilakukan perbaikan
silahkan clone ulang 
git clone https://github.com/pojokcodeid/nvim-lazy-basic.git ~/.config/nvim

dan load ulang semua lib

**Comment by rezafikkri** [comment]
oke siap
