### ISSUE TITLE
Muncul Warning saat save project typescript

### ISSUE THREAD

**Issue by ifqygazhar** [pojokcodeid/nvim-lazy#8]
Halo saya sudah install tsserver dan prettier tapi pas save file .ts suka muncul warning [LSP][null-ls] timeout, solusinya gimana ya

**Comment by pojokcodeid** [comment]
mohon lampirkan capture errornya ...

**Comment by pojokcodeid** [comment]
sudah saya tambahkan config 
vim.g.pcode_format_timeout_ms = 5000
atau silahkan clone ulang basic configmnya

**Comment by ifqygazhar** [comment]
terima kasih 🙏
